import * as hal from 'hr.halcyon.EndpointClient';

export class TypescriptInputWithFileResult {
    private client: hal.HalEndpointClient;

    constructor(client: hal.HalEndpointClient) {
        this.client = client;
    }

    private strongData: TypescriptInputWithFile = undefined;
    public get data(): TypescriptInputWithFile {
        this.strongData = this.strongData || this.client.GetData<TypescriptInputWithFile>();
        return this.strongData;
    }
}
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v9.10.10.0 (Newtonsoft.Json v10.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export interface InputWithFile {
    File?: any;
}
